### ISSUE TITLE
Is there an advanced search we can do that shows all issues across all repos labelled "good beginner issue"

### ISSUE THREAD

**Issue by KadeMorton** [aletheia-foundation/aletheia-admin#38]
Reason being we can put a link to the search in our Contributing file so literally all good beginner issues are viewable from one click. Otherwise we will need to list out instructions of going into the repos individually to look for them.

**Comment by rcdun** [comment]
I think [https://github.com/search?q=org%3Aaletheia-foundation+label%3A%22good+beginner+issue%22&state=open&type=Issues](https://github.com/search?q=org%3Aaletheia-foundation+label%3A%22good+beginner+issue%22&state=open&type=Issues) works. It's giving me two results, which I think seems right. I'll add it to the Contributing file.

Edit: changed it to the view which only shows _open_ issues.

**Comment by KadeMorton** [comment]
Great, this is exactly what we need! Thanks @rcdun !
